CREATE TABLE IF NOT EXISTS `players`(
    `id` INT UNSIGNED AUTO_INCREMENT,
    `code` VARCHAR(128) NOT NULL DEFAULT '',
    `country` VARCHAR(128 ) NOT NULL DEFAULT '',
    `country_en` VARCHAR(128 ) NOT NULL DEFAULT '',
    `display_affiliation` VARCHAR(128 ) NOT NULL DEFAULT '',
    `display_name` VARCHAR(128 ) NOT NULL DEFAULT '',
    `dob` VARCHAR(128 ) NOT NULL DEFAULT '',
    `draft_year` VARCHAR(128 ) NOT NULL DEFAULT '',
    `experience` VARCHAR(128 ) NOT NULL DEFAULT '',
    `first_initial` VARCHAR(128 ) NOT NULL DEFAULT '',
    `first_name` VARCHAR(128 ) NOT NULL DEFAULT '',
    `first_name_en` VARCHAR(128 ) NOT NULL DEFAULT '',
    `height` VARCHAR(128 ) NOT NULL DEFAULT '',
    `jersey_no` VARCHAR(128 ) NOT NULL DEFAULT '',
    `last_name` VARCHAR(128 ) NOT NULL DEFAULT '',
    `last_name_en` VARCHAR(128 ) NOT NULL DEFAULT '',
    `league_id` VARCHAR(128 ) NOT NULL DEFAULT '',
    `player_id` VARCHAR(128 ) NOT NULL DEFAULT '',
    `position` VARCHAR(128 ) NOT NULL DEFAULT '',
    `school_type` VARCHAR(128 ) NOT NULL DEFAULT '',
    `weight` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_abbr` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_city` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_city_en` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_code` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_conference` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_display_abbr` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_display_conference` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_division` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_id` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_is_all_star_team` SMALLINT(1) NOT NULL DEFAULT 1,
    `team_is_league_team` SMALLINT(1) NOT NULL DEFAULT 1,
    `team_league_id` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_name` VARCHAR(128 ) NOT NULL DEFAULT '',
    `team_name_en` VARCHAR(128 ) NOT NULL DEFAULT '',
    PRIMARY KEY ( `id` )
);