server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/nba?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: nba
    password: nba
    type: com.alibaba.druid.pool.DruidDataSource
    name: mysql

# ≈‰÷√slq¥Ú”°»’÷æ
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

es:
  host: 192.168.1.102
  port: 9200
  schema: http