server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/nba?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: nba
    password: nba
    type: com.alibaba.druid.pool.DruidDataSource
    name: mysql
  redis:
    port: 6379
    database: 0
    password: sOmE_sEcUrE_pAsS
    sentinel:
      master: mymaster
      nodes: 192.168.1.103:26379,192.168.1.104:26379,192.168.1.105:26379
  rabbitmq:
    host: 192.168.1.103
    port: 5672
    username: admin
    password: abc123_
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
    publisher-confirm-type: correlated
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 3176475291@qq.com #发送邮件的邮箱地址
    password: uyeqltvlyeendefi #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 3176475291@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

es:
  host: 192.168.1.102
  port: 9200
  schema: http

logging:
  file:
    path: logs
    max-size: 100MB
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    root: INFO

example:
  service:
    enabled: true
    prefix: "####"
    suffix: "@@@@"