spring:
  application:
    name: mecury-dubbo-consumer
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

server:
  port: 8888

dubbo:
  application:
    id: mecury-dubbo-consumer
    name: mecury-dubbo-consumer
  registry:
    protocol: zookeeper
    address: 192.168.1.103:2181,192.168.1.104:2181,192.168.1.105:2181