dubbo:
  application:
    name: mecury-dubbo-provider
    id: mecury-dubbo-provider
  registry:
    protocol: zookeeper
    address: 192.168.1.103:2181,192.168.1.104:2181,192.168.1.105:2181
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 10000
    retries: 3
    delay: -1
  scan:
    base-packages: com.galaxy.mecury.dubbo.provider.service.impl

server:
  port: 9999

spring:
  application:
    name: mecury-dubbo-provider
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration