// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.galaxy.venus.qq.protobuf;

public final class Addressbook {
  private Addressbook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MOBILE = 0;</code>
     */
    MOBILE(0),
    /**
     * <code>HOME = 1;</code>
     */
    HOME(1),
    /**
     * <code>WORK = 2;</code>
     */
    WORK(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOBILE = 0;</code>
     */
    public static final int MOBILE_VALUE = 0;
    /**
     * <code>HOME = 1;</code>
     */
    public static final int HOME_VALUE = 1;
    /**
     * <code>WORK = 2;</code>
     */
    public static final int WORK_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return MOBILE;
        case 1: return HOME;
        case 2: return WORK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            @java.lang.Override
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return PhoneTypeVerifier.INSTANCE;
    }

    private static final class PhoneTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PhoneTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return PhoneType.forNumber(number) != null;
            }
          };

    private final int value;

    private PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PhoneType)
  }

  public interface AddressBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressBook)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .Person people = 1;</code>
     */
    java.util.List<com.galaxy.venus.qq.protobuf.Addressbook.Person> 
        getPeopleList();
    /**
     * <code>repeated .Person people = 1;</code>
     */
    com.galaxy.venus.qq.protobuf.Addressbook.Person getPeople(int index);
    /**
     * <code>repeated .Person people = 1;</code>
     */
    int getPeopleCount();
  }
  /**
   * Protobuf type {@code AddressBook}
   */
  public  static final class AddressBook extends
      com.google.protobuf.GeneratedMessageLite<
          AddressBook, AddressBook.Builder> implements
      // @@protoc_insertion_point(message_implements:AddressBook)
      AddressBookOrBuilder {
    private AddressBook() {
      people_ = emptyProtobufList();
    }
    public static final int PEOPLE_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.galaxy.venus.qq.protobuf.Addressbook.Person> people_;
    /**
     * <code>repeated .Person people = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.galaxy.venus.qq.protobuf.Addressbook.Person> getPeopleList() {
      return people_;
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public java.util.List<? extends com.galaxy.venus.qq.protobuf.Addressbook.PersonOrBuilder> 
        getPeopleOrBuilderList() {
      return people_;
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    @java.lang.Override
    public int getPeopleCount() {
      return people_.size();
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    @java.lang.Override
    public com.galaxy.venus.qq.protobuf.Addressbook.Person getPeople(int index) {
      return people_.get(index);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    public com.galaxy.venus.qq.protobuf.Addressbook.PersonOrBuilder getPeopleOrBuilder(
        int index) {
      return people_.get(index);
    }
    private void ensurePeopleIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.galaxy.venus.qq.protobuf.Addressbook.Person> tmp = people_;
      if (!tmp.isModifiable()) {
        people_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void setPeople(
        int index, com.galaxy.venus.qq.protobuf.Addressbook.Person value) {
      value.getClass();
  ensurePeopleIsMutable();
      people_.set(index, value);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addPeople(com.galaxy.venus.qq.protobuf.Addressbook.Person value) {
      value.getClass();
  ensurePeopleIsMutable();
      people_.add(value);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addPeople(
        int index, com.galaxy.venus.qq.protobuf.Addressbook.Person value) {
      value.getClass();
  ensurePeopleIsMutable();
      people_.add(index, value);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void addAllPeople(
        java.lang.Iterable<? extends com.galaxy.venus.qq.protobuf.Addressbook.Person> values) {
      ensurePeopleIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, people_);
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void clearPeople() {
      people_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Person people = 1;</code>
     */
    private void removePeople(int index) {
      ensurePeopleIsMutable();
      people_.remove(index);
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.galaxy.venus.qq.protobuf.Addressbook.AddressBook prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.galaxy.venus.qq.protobuf.Addressbook.AddressBook, Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressBook)
        com.galaxy.venus.qq.protobuf.Addressbook.AddressBookOrBuilder {
      // Construct using com.galaxy.venus.qq.protobuf.Addressbook.AddressBook.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .Person people = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.galaxy.venus.qq.protobuf.Addressbook.Person> getPeopleList() {
        return java.util.Collections.unmodifiableList(
            instance.getPeopleList());
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      @java.lang.Override
      public int getPeopleCount() {
        return instance.getPeopleCount();
      }/**
       * <code>repeated .Person people = 1;</code>
       */
      @java.lang.Override
      public com.galaxy.venus.qq.protobuf.Addressbook.Person getPeople(int index) {
        return instance.getPeople(index);
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder setPeople(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.Person value) {
        copyOnWrite();
        instance.setPeople(index, value);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder setPeople(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.Person.Builder builderForValue) {
        copyOnWrite();
        instance.setPeople(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(com.galaxy.venus.qq.protobuf.Addressbook.Person value) {
        copyOnWrite();
        instance.addPeople(value);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.Person value) {
        copyOnWrite();
        instance.addPeople(index, value);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(
          com.galaxy.venus.qq.protobuf.Addressbook.Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPeople(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addPeople(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.Person.Builder builderForValue) {
        copyOnWrite();
        instance.addPeople(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder addAllPeople(
          java.lang.Iterable<? extends com.galaxy.venus.qq.protobuf.Addressbook.Person> values) {
        copyOnWrite();
        instance.addAllPeople(values);
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder clearPeople() {
        copyOnWrite();
        instance.clearPeople();
        return this;
      }
      /**
       * <code>repeated .Person people = 1;</code>
       */
      public Builder removePeople(int index) {
        copyOnWrite();
        instance.removePeople(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddressBook)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.galaxy.venus.qq.protobuf.Addressbook.AddressBook();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "people_",
              com.galaxy.venus.qq.protobuf.Addressbook.Person.class,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.galaxy.venus.qq.protobuf.Addressbook.AddressBook> parser = PARSER;
          if (parser == null) {
            synchronized (com.galaxy.venus.qq.protobuf.Addressbook.AddressBook.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.galaxy.venus.qq.protobuf.Addressbook.AddressBook>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AddressBook)
    private static final com.galaxy.venus.qq.protobuf.Addressbook.AddressBook DEFAULT_INSTANCE;
    static {
      AddressBook defaultInstance = new AddressBook();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AddressBook.class, defaultInstance);
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.AddressBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AddressBook> PARSER;

    public static com.google.protobuf.Parser<AddressBook> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>float money = 4;</code>
     * @return The money.
     */
    float getMoney();

    /**
     * <code>bool work_status = 5;</code>
     * @return The workStatus.
     */
    boolean getWorkStatus();

    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    java.util.List<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> 
        getPhonesList();
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber getPhones(int index);
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    int getPhonesCount();

    /**
     * <code>.MyMessage maps = 7;</code>
     * @return Whether the maps field is set.
     */
    boolean hasMaps();
    /**
     * <code>.MyMessage maps = 7;</code>
     * @return The maps.
     */
    com.galaxy.venus.qq.protobuf.Addressbook.MyMessage getMaps();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageLite<
          Person, Person.Builder> implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    private Person() {
      name_ = "";
      email_ = "";
      phones_ = emptyProtobufList();
    }
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 2;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.String email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     */
    private void setEmail(
        java.lang.String value) {
      value.getClass();
  
      email_ = value;
    }
    /**
     * <code>string email = 3;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();
      
    }

    public static final int MONEY_FIELD_NUMBER = 4;
    private float money_;
    /**
     * <code>float money = 4;</code>
     * @return The money.
     */
    @java.lang.Override
    public float getMoney() {
      return money_;
    }
    /**
     * <code>float money = 4;</code>
     * @param value The money to set.
     */
    private void setMoney(float value) {
      
      money_ = value;
    }
    /**
     * <code>float money = 4;</code>
     */
    private void clearMoney() {
      
      money_ = 0F;
    }

    public static final int WORK_STATUS_FIELD_NUMBER = 5;
    private boolean workStatus_;
    /**
     * <code>bool work_status = 5;</code>
     * @return The workStatus.
     */
    @java.lang.Override
    public boolean getWorkStatus() {
      return workStatus_;
    }
    /**
     * <code>bool work_status = 5;</code>
     * @param value The workStatus to set.
     */
    private void setWorkStatus(boolean value) {
      
      workStatus_ = value;
    }
    /**
     * <code>bool work_status = 5;</code>
     */
    private void clearWorkStatus() {
      
      workStatus_ = false;
    }

    public static final int PHONES_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.ProtobufList<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> phones_;
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    @java.lang.Override
    public java.util.List<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    public java.util.List<? extends com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumberOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    @java.lang.Override
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    @java.lang.Override
    public com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    public com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }
    private void ensurePhonesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> tmp = phones_;
      if (!tmp.isModifiable()) {
        phones_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    private void setPhones(
        int index, com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber value) {
      value.getClass();
  ensurePhonesIsMutable();
      phones_.set(index, value);
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    private void addPhones(com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber value) {
      value.getClass();
  ensurePhonesIsMutable();
      phones_.add(value);
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    private void addPhones(
        int index, com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber value) {
      value.getClass();
  ensurePhonesIsMutable();
      phones_.add(index, value);
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    private void addAllPhones(
        java.lang.Iterable<? extends com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> values) {
      ensurePhonesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, phones_);
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    private void clearPhones() {
      phones_ = emptyProtobufList();
    }
    /**
     * <code>repeated .PhoneNumber phones = 6;</code>
     */
    private void removePhones(int index) {
      ensurePhonesIsMutable();
      phones_.remove(index);
    }

    public static final int MAPS_FIELD_NUMBER = 7;
    private com.galaxy.venus.qq.protobuf.Addressbook.MyMessage maps_;
    /**
     * <code>.MyMessage maps = 7;</code>
     */
    @java.lang.Override
    public boolean hasMaps() {
      return maps_ != null;
    }
    /**
     * <code>.MyMessage maps = 7;</code>
     */
    @java.lang.Override
    public com.galaxy.venus.qq.protobuf.Addressbook.MyMessage getMaps() {
      return maps_ == null ? com.galaxy.venus.qq.protobuf.Addressbook.MyMessage.getDefaultInstance() : maps_;
    }
    /**
     * <code>.MyMessage maps = 7;</code>
     */
    private void setMaps(com.galaxy.venus.qq.protobuf.Addressbook.MyMessage value) {
      value.getClass();
  maps_ = value;
      
      }
    /**
     * <code>.MyMessage maps = 7;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeMaps(com.galaxy.venus.qq.protobuf.Addressbook.MyMessage value) {
      value.getClass();
  if (maps_ != null &&
          maps_ != com.galaxy.venus.qq.protobuf.Addressbook.MyMessage.getDefaultInstance()) {
        maps_ =
          com.galaxy.venus.qq.protobuf.Addressbook.MyMessage.newBuilder(maps_).mergeFrom(value).buildPartial();
      } else {
        maps_ = value;
      }
      
    }
    /**
     * <code>.MyMessage maps = 7;</code>
     */
    private void clearMaps() {  maps_ = null;
      
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.galaxy.venus.qq.protobuf.Addressbook.Person prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.galaxy.venus.qq.protobuf.Addressbook.Person, Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.galaxy.venus.qq.protobuf.Addressbook.PersonOrBuilder {
      // Construct using com.galaxy.venus.qq.protobuf.Addressbook.Person.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>int32 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>float money = 4;</code>
       * @return The money.
       */
      @java.lang.Override
      public float getMoney() {
        return instance.getMoney();
      }
      /**
       * <code>float money = 4;</code>
       * @param value The money to set.
       * @return This builder for chaining.
       */
      public Builder setMoney(float value) {
        copyOnWrite();
        instance.setMoney(value);
        return this;
      }
      /**
       * <code>float money = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoney() {
        copyOnWrite();
        instance.clearMoney();
        return this;
      }

      /**
       * <code>bool work_status = 5;</code>
       * @return The workStatus.
       */
      @java.lang.Override
      public boolean getWorkStatus() {
        return instance.getWorkStatus();
      }
      /**
       * <code>bool work_status = 5;</code>
       * @param value The workStatus to set.
       * @return This builder for chaining.
       */
      public Builder setWorkStatus(boolean value) {
        copyOnWrite();
        instance.setWorkStatus(value);
        return this;
      }
      /**
       * <code>bool work_status = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkStatus() {
        copyOnWrite();
        instance.clearWorkStatus();
        return this;
      }

      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      @java.lang.Override
      public java.util.List<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> getPhonesList() {
        return java.util.Collections.unmodifiableList(
            instance.getPhonesList());
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      @java.lang.Override
      public int getPhonesCount() {
        return instance.getPhonesCount();
      }/**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      @java.lang.Override
      public com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber getPhones(int index) {
        return instance.getPhones(index);
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder setPhones(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber value) {
        copyOnWrite();
        instance.setPhones(index, value);
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder setPhones(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setPhones(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder addPhones(com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber value) {
        copyOnWrite();
        instance.addPhones(value);
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder addPhones(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber value) {
        copyOnWrite();
        instance.addPhones(index, value);
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder addPhones(
          com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhones(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder addPhones(
          int index, com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addPhones(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> values) {
        copyOnWrite();
        instance.addAllPhones(values);
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder clearPhones() {
        copyOnWrite();
        instance.clearPhones();
        return this;
      }
      /**
       * <code>repeated .PhoneNumber phones = 6;</code>
       */
      public Builder removePhones(int index) {
        copyOnWrite();
        instance.removePhones(index);
        return this;
      }

      /**
       * <code>.MyMessage maps = 7;</code>
       */
      @java.lang.Override
      public boolean hasMaps() {
        return instance.hasMaps();
      }
      /**
       * <code>.MyMessage maps = 7;</code>
       */
      @java.lang.Override
      public com.galaxy.venus.qq.protobuf.Addressbook.MyMessage getMaps() {
        return instance.getMaps();
      }
      /**
       * <code>.MyMessage maps = 7;</code>
       */
      public Builder setMaps(com.galaxy.venus.qq.protobuf.Addressbook.MyMessage value) {
        copyOnWrite();
        instance.setMaps(value);
        return this;
        }
      /**
       * <code>.MyMessage maps = 7;</code>
       */
      public Builder setMaps(
          com.galaxy.venus.qq.protobuf.Addressbook.MyMessage.Builder builderForValue) {
        copyOnWrite();
        instance.setMaps(builderForValue.build());
        return this;
      }
      /**
       * <code>.MyMessage maps = 7;</code>
       */
      public Builder mergeMaps(com.galaxy.venus.qq.protobuf.Addressbook.MyMessage value) {
        copyOnWrite();
        instance.mergeMaps(value);
        return this;
      }
      /**
       * <code>.MyMessage maps = 7;</code>
       */
      public Builder clearMaps() {  copyOnWrite();
        instance.clearMaps();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.galaxy.venus.qq.protobuf.Addressbook.Person();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
              "id_",
              "email_",
              "money_",
              "workStatus_",
              "phones_",
              com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber.class,
              "maps_",
            };
            java.lang.String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0001\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0208\u0004\u0001\u0005\u0007\u0006\u001b\u0007\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.galaxy.venus.qq.protobuf.Addressbook.Person> parser = PARSER;
          if (parser == null) {
            synchronized (com.galaxy.venus.qq.protobuf.Addressbook.Person.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.galaxy.venus.qq.protobuf.Addressbook.Person>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Person)
    private static final com.galaxy.venus.qq.protobuf.Addressbook.Person DEFAULT_INSTANCE;
    static {
      Person defaultInstance = new Person();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Person.class, defaultInstance);
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Person> PARSER;

    public static com.google.protobuf.Parser<Person> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PhoneNumber)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.PhoneType type = 2;</code>
     * @return The type.
     */
    com.galaxy.venus.qq.protobuf.Addressbook.PhoneType getType();
  }
  /**
   * Protobuf type {@code PhoneNumber}
   */
  public  static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageLite<
          PhoneNumber, PhoneNumber.Builder> implements
      // @@protoc_insertion_point(message_implements:PhoneNumber)
      PhoneNumberOrBuilder {
    private PhoneNumber() {
      number_ = "";
    }
    public static final int NUMBER_FIELD_NUMBER = 1;
    private java.lang.String number_;
    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      return number_;
    }
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(number_);
    }
    /**
     * <code>string number = 1;</code>
     * @param value The number to set.
     */
    private void setNumber(
        java.lang.String value) {
      value.getClass();
  
      number_ = value;
    }
    /**
     * <code>string number = 1;</code>
     */
    private void clearNumber() {
      
      number_ = getDefaultInstance().getNumber();
    }
    /**
     * <code>string number = 1;</code>
     * @param value The bytes for number to set.
     */
    private void setNumberBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      number_ = value.toStringUtf8();
      
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PhoneType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.galaxy.venus.qq.protobuf.Addressbook.PhoneType getType() {
      com.galaxy.venus.qq.protobuf.Addressbook.PhoneType result = com.galaxy.venus.qq.protobuf.Addressbook.PhoneType.forNumber(type_);
      return result == null ? com.galaxy.venus.qq.protobuf.Addressbook.PhoneType.UNRECOGNIZED : result;
    }
    /**
     * <code>.PhoneType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     */
    private void setTypeValue(int value) {
        type_ = value;
    }
    /**
     * <code>.PhoneType type = 2;</code>
     * @param value The type to set.
     */
    private void setType(com.galaxy.venus.qq.protobuf.Addressbook.PhoneType value) {
      type_ = value.getNumber();
      
    }
    /**
     * <code>.PhoneType type = 2;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber, Builder> implements
        // @@protoc_insertion_point(builder_implements:PhoneNumber)
        com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumberOrBuilder {
      // Construct using com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        return instance.getNumber();
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        return instance.getNumberBytes();
      }
      /**
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setNumber(value);
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        copyOnWrite();
        instance.clearNumber();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNumberBytes(value);
        return this;
      }

      /**
       * <code>.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return instance.getTypeValue();
      }
      /**
       * <code>.PhoneType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        copyOnWrite();
        instance.setTypeValue(value);
        return this;
      }
      /**
       * <code>.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.galaxy.venus.qq.protobuf.Addressbook.PhoneType getType() {
        return instance.getType();
      }
      /**
       * <code>.PhoneType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.galaxy.venus.qq.protobuf.Addressbook.PhoneType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>.PhoneType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PhoneNumber)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "number_",
              "type_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\f" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber> parser = PARSER;
          if (parser == null) {
            synchronized (com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:PhoneNumber)
    private static final com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber DEFAULT_INSTANCE;
    static {
      PhoneNumber defaultInstance = new PhoneNumber();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PhoneNumber.class, defaultInstance);
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PhoneNumber> PARSER;

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    int getMapfieldCount();
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    boolean containsMapfield(
        int key);
    /**
     * Use {@link #getMapfieldMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getMapfield();
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getMapfieldMap();
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */

    int getMapfieldOrDefault(
        int key,
        int defaultValue);
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */

    int getMapfieldOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code MyMessage}
   */
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageLite<
          MyMessage, MyMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
    private MyMessage() {
    }
    public static final int MAPFIELD_FIELD_NUMBER = 1;
    private static final class MapfieldDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.Integer, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.Integer, java.lang.Integer> mapfield_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.Integer, java.lang.Integer>
    internalGetMapfield() {
      return mapfield_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.Integer, java.lang.Integer>
    internalGetMutableMapfield() {
      if (!mapfield_.isMutable()) {
        mapfield_ = mapfield_.mutableCopy();
      }
      return mapfield_;
    }
    @java.lang.Override

    public int getMapfieldCount() {
      return internalGetMapfield().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    @java.lang.Override

    public boolean containsMapfield(
        int key) {
      
      return internalGetMapfield().containsKey(key);
    }
    /**
     * Use {@link #getMapfieldMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getMapfield() {
      return getMapfieldMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getMapfieldMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetMapfield());
    }
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    @java.lang.Override

    public int getMapfieldOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetMapfield();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    @java.lang.Override

    public int getMapfieldOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetMapfield();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
     */
    private java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableMapfieldMap() {
      return internalGetMutableMapfield();
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.galaxy.venus.qq.protobuf.Addressbook.MyMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.galaxy.venus.qq.protobuf.Addressbook.MyMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        com.galaxy.venus.qq.protobuf.Addressbook.MyMessageOrBuilder {
      // Construct using com.galaxy.venus.qq.protobuf.Addressbook.MyMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      @java.lang.Override

      public int getMapfieldCount() {
        return instance.getMapfieldMap().size();
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */
      @java.lang.Override

      public boolean containsMapfield(
          int key) {
        
        return instance.getMapfieldMap().containsKey(key);
      }

      public Builder clearMapfield() {
        copyOnWrite();
        instance.getMutableMapfieldMap().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */

      public Builder removeMapfield(
          int key) {
        
        copyOnWrite();
        instance.getMutableMapfieldMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getMapfieldMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer> getMapfield() {
        return getMapfieldMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, java.lang.Integer> getMapfieldMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getMapfieldMap());
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */
      @java.lang.Override

      public int getMapfieldOrDefault(
          int key,
          int defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            instance.getMapfieldMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */
      @java.lang.Override

      public int getMapfieldOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            instance.getMapfieldMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */
      public Builder putMapfield(
          int key,
          int value) {
        
        
        copyOnWrite();
        instance.getMutableMapfieldMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; mapfield = 1;</code>
       */
      public Builder putAllMapfield(
          java.util.Map<java.lang.Integer, java.lang.Integer> values) {
        copyOnWrite();
        instance.getMutableMapfieldMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.galaxy.venus.qq.protobuf.Addressbook.MyMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "mapfield_",
              MapfieldDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.galaxy.venus.qq.protobuf.Addressbook.MyMessage> parser = PARSER;
          if (parser == null) {
            synchronized (com.galaxy.venus.qq.protobuf.Addressbook.MyMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.galaxy.venus.qq.protobuf.Addressbook.MyMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:MyMessage)
    private static final com.galaxy.venus.qq.protobuf.Addressbook.MyMessage DEFAULT_INSTANCE;
    static {
      MyMessage defaultInstance = new MyMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MyMessage.class, defaultInstance);
    }

    public static com.galaxy.venus.qq.protobuf.Addressbook.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MyMessage> PARSER;

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
